### ISSUE TITLE
How to generate points.txt using random image

### ISSUE THREAD

**Issue by shiyingZhang90** [ESanchezLozano/GANnotation#11]
Hi,
I wanna to generate the video using my own image, and my understanding is to use util's process_image function: process_image(image,points,angle=0, flip=False, sigma=1,size=128, tight=16):
Yet, I'm wondering how do people get initial landmark points from? Still use util script or just define null array to points initially?

**Comment by ESanchezLozano** [comment]
Hi,

You have to extract the points with any landmark detector of your wish. Otherwise you can crop the image manually to adjust it to more or less the standards expected by the network.

**Comment by sanjeelparekh** [comment]
Hi @ESanchezLozano,

Thanks for making your code public! It is very helpful. I had questions related to a similar issue i.e. how to extract network compatible landmark points or use a detector of my choice.

If I understand well, the released generator model uses 66 target landmark points. I have the following questions:
 - Which detector did you use to extract these 66 points (or a paper that points to such a detector will be very useful)?
 - Is there an automatic or predefined manual way to make the input landmark points "generator network-compatible" when I use any landmark detector of my choice, for instance, dlib which outputs 68 instead of 66 points?

Thanks!

@shiyingZhang90  - have you already figured this out? will be good to hear your findings.

**Comment by ESanchezLozano** [comment]
Hi,


The points were tracked using my previously published face-tracker ( E. Sanchez-Lozano et al. A functional regression approach to facial landmark tracking. IEEE TPAMI 2018). However, any face tracker can be of use in this sense. The only difference between the 68 and 66 point configuration is the two extra points in the mouth corners. From the 68 points, if you remove point 61 and 65 (assuming starting index of 1), then you get the 66 point configuration used for this repo. 

I hope this helps, please let me know otherwise.

**Comment by sanjeelparekh** [comment]
Thanks for your quick response. This answers my question.
